-- Clockworks C Compiler — root import
import CCC.Syntax.AST
import CCC.Syntax.PtrState
import CCC.Syntax.Build
import CCC.Error.Report
import CCC.Parse.Token
import CCC.Parse.Lex
import CCC.Parse.Parse
import CCC.Verify.FlowState
import CCC.Verify.TypeSize
import CCC.Verify.PointerSafety
import CCC.Verify.NullCheck
import CCC.Verify.BranchAnalysis
import CCC.Verify.BoundsCheck
import CCC.Verify.SymbolCheck
import CCC.Verify.Verify
import CCC.Emit.X86
import CCC.Emit.Runtime
import CCC.Emit.EmitX86
import CCC.IR.IR
import CCC.Preprocess.Preprocess
import CCC.Emit.AArch64
import CCC.Emit.EmitAArch64
-- Feature stubs (25 features × 4 files)
import CCC.Features.Preprocess.Parse
import CCC.Features.Preprocess.Verify
import CCC.Features.Preprocess.Lower
import CCC.Features.Preprocess.Test
import CCC.Features.StringLit.Parse
import CCC.Features.StringLit.Verify
import CCC.Features.StringLit.Lower
import CCC.Features.StringLit.Test
import CCC.Features.Ternary.Parse
import CCC.Features.Ternary.Verify
import CCC.Features.Ternary.Lower
import CCC.Features.Ternary.Test
import CCC.Features.CompAssign.Parse
import CCC.Features.CompAssign.Verify
import CCC.Features.CompAssign.Lower
import CCC.Features.CompAssign.Test
import CCC.Features.IncDec.Parse
import CCC.Features.IncDec.Verify
import CCC.Features.IncDec.Lower
import CCC.Features.IncDec.Test
import CCC.Features.Bitwise.Parse
import CCC.Features.Bitwise.Verify
import CCC.Features.Bitwise.Lower
import CCC.Features.Bitwise.Test
import CCC.Features.DoWhile.Parse
import CCC.Features.DoWhile.Verify
import CCC.Features.DoWhile.Lower
import CCC.Features.DoWhile.Test
import CCC.Features.BreakCont.Parse
import CCC.Features.BreakCont.Verify
import CCC.Features.BreakCont.Lower
import CCC.Features.BreakCont.Test
import CCC.Features.Switch.Parse
import CCC.Features.Switch.Verify
import CCC.Features.Switch.Lower
import CCC.Features.Switch.Test
import CCC.Features.Goto.Parse
import CCC.Features.Goto.Verify
import CCC.Features.Goto.Lower
import CCC.Features.Goto.Test
import CCC.Features.Enum.Parse
import CCC.Features.Enum.Verify
import CCC.Features.Enum.Lower
import CCC.Features.Enum.Test
import CCC.Features.Union.Parse
import CCC.Features.Union.Verify
import CCC.Features.Union.Lower
import CCC.Features.Union.Test
import CCC.Features.Typedef.Parse
import CCC.Features.Typedef.Verify
import CCC.Features.Typedef.Lower
import CCC.Features.Typedef.Test
import CCC.Features.FuncPtr.Parse
import CCC.Features.FuncPtr.Verify
import CCC.Features.FuncPtr.Lower
import CCC.Features.FuncPtr.Test
import CCC.Features.Cast.Parse
import CCC.Features.Cast.Verify
import CCC.Features.Cast.Lower
import CCC.Features.Cast.Test
import CCC.Features.Float.Parse
import CCC.Features.Float.Verify
import CCC.Features.Float.Lower
import CCC.Features.Float.Test
import CCC.Features.Extern.Parse
import CCC.Features.Extern.Verify
import CCC.Features.Extern.Lower
import CCC.Features.Extern.Test
import CCC.Features.InitList.Parse
import CCC.Features.InitList.Verify
import CCC.Features.InitList.Lower
import CCC.Features.InitList.Test
import CCC.Features.IntWidths.Parse
import CCC.Features.IntWidths.Verify
import CCC.Features.IntWidths.Lower
import CCC.Features.IntWidths.Test
import CCC.Features.Qualifiers.Parse
import CCC.Features.Qualifiers.Verify
import CCC.Features.Qualifiers.Lower
import CCC.Features.Qualifiers.Test
import CCC.Features.Comma.Parse
import CCC.Features.Comma.Verify
import CCC.Features.Comma.Lower
import CCC.Features.Comma.Test
import CCC.Features.MultiDecl.Parse
import CCC.Features.MultiDecl.Verify
import CCC.Features.MultiDecl.Lower
import CCC.Features.MultiDecl.Test
import CCC.Features.Attribute.Parse
import CCC.Features.Attribute.Verify
import CCC.Features.Attribute.Lower
import CCC.Features.Attribute.Test
import CCC.Features.StorageClass.Parse
import CCC.Features.StorageClass.Verify
import CCC.Features.StorageClass.Lower
import CCC.Features.StorageClass.Test
import CCC.Features.StructByValue.Parse
import CCC.Features.StructByValue.Verify
import CCC.Features.StructByValue.Lower
import CCC.Features.StructByValue.Test
-- Backend stubs (4 backends × 4 files)
import CCC.Backend.X86_64.Regs
import CCC.Backend.X86_64.ABI
import CCC.Backend.X86_64.Select
import CCC.Backend.X86_64.Emit
import CCC.Backend.AArch64.Regs
import CCC.Backend.AArch64.ABI
import CCC.Backend.AArch64.Select
import CCC.Backend.AArch64.Emit
import CCC.Backend.RISCV.Regs
import CCC.Backend.RISCV.ABI
import CCC.Backend.RISCV.Select
import CCC.Backend.RISCV.Emit
import CCC.Backend.X86_32.Regs
import CCC.Backend.X86_32.ABI
import CCC.Backend.X86_32.Select
import CCC.Backend.X86_32.Emit
import CCC.Contracts
import CCC.Pipeline
